export const metadata = {
  title: "App with API route",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <header>header</header>
          {children}
        </div>
      </body>
    </html>
  );
}
